version: '3'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    depends_on:
      - mongodb
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8989 

  crawlab:
    image: crawlabteam/crawlab
    build: 
      context: .
      dockerfile: ./crawlab/Dockerfile
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongodb"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    # environment:
    #   - "MONGO_INITDB_DATABASE=${MONGO_DB}"
    #   - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
    #   - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod --quiet --logpath /dev/null