[tool.poetry]
name = "fastapi-mongodb"
version = "0.1.0"
description = ""
authors = ["Kien Nguyen <kien@nutuki.com>"]
readme = "README.md"
packages = [{include = "fastapi_mongodb"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.92.0"
motor = "^3.1.1"
uvicorn = "^0.20.0"
pytest-cov = "^4.0.0"
httpx = "^0.23.3"
rich = "^13.3.1"
black = "^23.0.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
